import { type NextPage } from "next";
import Head from "next/head";
import React from "react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  if (!hello.data) {
    return <p>Loading ...</p>;
  }
  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <p>
      {hello.data.greeting}
      </p>
      </main>
    </>
  );
};

export default Home;
