import Head from "next/head";

interface PageContainerProps {
  title: String;
  children?: React.ReactElement[];
}

export const PageContainer = ({ title, children }: PageContainerProps) => {
  return(
  <>
    <Head>
      <title>{ title }</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
      />
    </Head>
    <div className="w-full min-h-screen bg-neutral-200">
    { children }
    </div>
  </>
  );
}
